'''
Define headers for tracklet files

'''
import tensorflow as tf
import tensorflow_datasets as tfds

#all raw data from .trk files.
header_all = ['NEO',
          'objectID',
          'trkID',
          'JDUTC_0',
          'X_0',
          'Y_0',
          'Z_0',
          'M_0',
          'sigmaJDUTC_0',
          'sigmaX_0',
          'sigmaY_0',
          'sigmaZ_0',
          'sigmaM_0',
          'solar_ang_0',
          'lunar_ang_0',
          'jovian_ang_0',
          'JDUTC_1',
          'X_1',
          'Y_1',
          'Z_1',
          'M_1',
          'sigmaJDUTC_1',
          'sigmaX_1',
          'sigmaY_1',
          'sigmaZ_1',
          'sigmaM_1',
          'solar_ang_1',
          'lunar_ang_1',
          'jovian_ang_1',
          'JDUTC_2',
          'X_2',
          'Y_2',
          'Z_2',
          'M_2',
          'sigmaJDUTC_2',
          'sigmaX_2',
          'sigmaY_2',
          'sigmaZ_2',
          'sigmaM_2',
          'solar_ang_2',
          'lunar_ang_2',
          'jovian_ang_2',
          'JDUTC_3',
          'X_3',
          'Y_3',
          'Z_3',
          'M_3',
          'sigmaJDUTC_3',
          'sigmaX_3',
          'sigmaY_3',
          'sigmaZ_3',
          'sigmaM_3',
          'solar_ang_3',
          'lunar_ang_3',
          'jovian_ang_3',
          'JDUTC_4',
          'X_4',
          'Y_4',
          'Z_4',
          'M_4',
          'sigmaJDUTC_4',
          'sigmaX_4',
          'sigmaY_4',
          'sigmaZ_4',
          'sigmaM_4',
          'solar_ang_4',
          'lunar_ang_4',
          'jovian_ang_4',
          'JDUTC_5',
          'X_5',
          'Y_5',
          'Z_5',
          'M_5',
          'sigmaJDUTC_5',
          'sigmaX_5',
          'sigmaY_5',
          'sigmaZ_5',
          'sigmaM_5',
          'solar_ang_5',
          'lunar_ang_5',
          'jovian_ang_5',
          'JDUTC_6',
          'X_6',
          'Y_6',
          'Z_6',
          'M_6',
          'sigmaJDUTC_6',
          'sigmaX_6',
          'sigmaY_6',
          'sigmaZ_6',
          'sigmaM_6',
          'solar_ang_6',
          'lunar_ang_6',
          'jovian_ang_6',
          'JDUTC_7',
          'X_7',
          'Y_7',
          'Z_7',
          'M_7',
          'sigmaJDUTC_7',
          'sigmaX_7',
          'sigmaY_7',
          'sigmaZ_7',
          'sigmaM_7',
          'solar_ang_7',
          'lunar_ang_7',
          'jovian_ang_7',
          'JDUTC_8',
          'X_8',
          'Y_8',
          'Z_8',
          'M_8',
          'sigmaJDUTC_8',
          'sigmaX_8',
          'sigmaY_8',
          'sigmaZ_8',
          'sigmaM_8',
          'solar_ang_8',
          'lunar_ang_8',
          'jovian_ang_8',
          'JDUTC_9',
          'X_9',
          'Y_9',
          'Z_9',
          'M_9',
          'sigmaJDUTC_9',
          'sigmaX_9',
          'sigmaY_9',
          'sigmaZ_9',
          'sigmaM_9',
          'solar_ang_9',
          'lunar_ang_9',
          'jovian_ang_9',
          'mu_ra_0',
          'mu_dec_0',
          'mu_sq_0',
          'mu_ra_1',
          'mu_dec_1',
          'mu_sq_1',
          'mu_ra_2',
          'mu_dec_2',
          'mu_sq_2',
          'mu_ra_3',
          'mu_dec_3',
          'mu_sq_3',
          'mu_ra_4',
          'mu_dec_4',
          'mu_sq_4',
          'mu_ra_5',
          'mu_dec_5',
          'mu_sq_5',
          'mu_ra_6',
          'mu_dec_6',
          'mu_sq_6',
          'mu_ra_7',
          'mu_dec_7',
          'mu_sq_7',
          'mu_ra_8',
          'mu_dec_8',
          'mu_sq_8',
          'd2_NEO_ALL',
          'd2_NEO_NEW']

#removed headers starting with sigma as they are all zeros
header_minus_sigma = ['NEO',
                      'objectID',
                      'trkID',
                      'JDUTC_0',
                      'X_0',
                      'Y_0',
                      'Z_0',
                      'M_0',
                      'solar_ang_0',
                      'lunar_ang_0',
                      'jovian_ang_0',
                      'JDUTC_1',
                      'X_1',
                      'Y_1',
                      'Z_1',
                      'M_1',
                      'solar_ang_1',
                      'lunar_ang_1',
                      'jovian_ang_1',
                      'JDUTC_2',
                      'X_2',
                      'Y_2',
                      'Z_2',
                      'M_2',
                      'solar_ang_2',
                      'lunar_ang_2',
                      'jovian_ang_2',
                      'JDUTC_3',
                      'X_3',
                      'Y_3',
                      'Z_3',
                      'M_3',
                      'solar_ang_3',
                      'lunar_ang_3',
                      'jovian_ang_3',
                      'JDUTC_4',
                      'X_4',
                      'Y_4',
                      'Z_4',
                      'M_4',
                      'solar_ang_4',
                      'lunar_ang_4',
                      'jovian_ang_4',
                      'JDUTC_5',
                      'X_5',
                      'Y_5',
                      'Z_5',
                      'M_5',
                      'solar_ang_5',
                      'lunar_ang_5',
                      'jovian_ang_5',
                      'JDUTC_6',
                      'X_6',
                      'Y_6',
                      'Z_6',
                      'M_6',
                      'solar_ang_6',
                      'lunar_ang_6',
                      'jovian_ang_6',
                      'JDUTC_7',
                      'X_7',
                      'Y_7',
                      'Z_7',
                      'M_7',
                      'solar_ang_7',
                      'lunar_ang_7',
                      'jovian_ang_7',
                      'JDUTC_8',
                      'X_8',
                      'Y_8',
                      'Z_8',
                      'M_8',
                      'solar_ang_8',
                      'lunar_ang_8',
                      'jovian_ang_8',
                      'JDUTC_9',
                      'X_9',
                      'Y_9',
                      'Z_9',
                      'M_9',
                      'solar_ang_9',
                      'lunar_ang_9',
                      'jovian_ang_9',
                      'mu_ra_0',
                      'mu_dec_0',
                      'mu_sq_0',
                      'mu_ra_1',
                      'mu_dec_1',
                      'mu_sq_1',
                      'mu_ra_2',
                      'mu_dec_2',
                      'mu_sq_2',
                      'mu_ra_3',
                      'mu_dec_3',
                      'mu_sq_3',
                      'mu_ra_4',
                      'mu_dec_4',
                      'mu_sq_4',
                      'mu_ra_5',
                      'mu_dec_5',
                      'mu_sq_5',
                      'mu_ra_6',
                      'mu_dec_6',
                      'mu_sq_6',
                      'mu_ra_7',
                      'mu_dec_7',
                      'mu_sq_7',
                      'mu_ra_8',
                      'mu_dec_8',
                      'mu_sq_8',
                      'd2_NEO_ALL',
                      'd2_NEO_NEW']

#removed last two features d2_NEO_ALL and d2_NEO_NEW
header_objID = ['NEO',
                'objectID',
                'trkID',
                'JDUTC_0',
                'X_0',
                'Y_0',
                'Z_0',
                'M_0',
                'solar_ang_0',
                'lunar_ang_0',
                'jovian_ang_0',
                'JDUTC_1',
                'X_1',
                'Y_1',
                'Z_1',
                'M_1',
                'solar_ang_1',
                'lunar_ang_1',
                'jovian_ang_1',
                'JDUTC_2',
                'X_2',
                'Y_2',
                'Z_2',
                'M_2',
                'solar_ang_2',
                'lunar_ang_2',
                'jovian_ang_2',
                'JDUTC_3',
                'X_3',
                'Y_3',
                'Z_3',
                'M_3',
                'solar_ang_3',
                'lunar_ang_3',
                'jovian_ang_3',
                'JDUTC_4',
                'X_4',
                'Y_4',
                'Z_4',
                'M_4',
                'solar_ang_4',
                'lunar_ang_4',
                'jovian_ang_4',
                'JDUTC_5',
                'X_5',
                'Y_5',
                'Z_5',
                'M_5',
                'solar_ang_5',
                'lunar_ang_5',
                'jovian_ang_5',
                'JDUTC_6',
                'X_6',
                'Y_6',
                'Z_6',
                'M_6',
                'solar_ang_6',
                'lunar_ang_6',
                'jovian_ang_6',
                'JDUTC_7',
                'X_7',
                'Y_7',
                'Z_7',
                'M_7',
                'solar_ang_7',
                'lunar_ang_7',
                'jovian_ang_7',
                'JDUTC_8',
                'X_8',
                'Y_8',
                'Z_8',
                'M_8',
                'solar_ang_8',
                'lunar_ang_8',
                'jovian_ang_8',
                'JDUTC_9',
                'X_9',
                'Y_9',
                'Z_9',
                'M_9',
                'solar_ang_9',
                'lunar_ang_9',
                'jovian_ang_9',
                'mu_ra_0',
                'mu_dec_0',
                'mu_sq_0',
                'mu_ra_1',
                'mu_dec_1',
                'mu_sq_1',
                'mu_ra_2',
                'mu_dec_2',
                'mu_sq_2',
                'mu_ra_3',
                'mu_dec_3',
                'mu_sq_3',
                'mu_ra_4',
                'mu_dec_4',
                'mu_sq_4',
                'mu_ra_5',
                'mu_dec_5',
                'mu_sq_5',
                'mu_ra_6',
                'mu_dec_6',
                'mu_sq_6',
                'mu_ra_7',
                'mu_dec_7',
                'mu_sq_7',
                'mu_ra_8',
                'mu_dec_8',
                'mu_sq_8']

#removed objectID and trkID features only remaining features are labels and numeric columns for training
header_numeric_features = tfds.features.FeaturesDict({'NEO' : tf.float32,
                                                      'JDUTC_0' : tf.float32,
                                                      'X_0' : tf.float32,
                                                      'Y_0' : tf.float32,
                                                      'Z_0' : tf.float32,
                                                      'M_0' : tf.float32,
                                                      'JDUTC_1' : tf.float32,
                                                      'X_1' : tf.float32,
                                                      'Y_1' : tf.float32,
                                                      'Z_1' : tf.float32,
                                                      'M_1' : tf.float32,
                                                      'JDUTC_2' : tf.float32,
                                                      'X_2' : tf.float32,
                                                      'Y_2' : tf.float32,
                                                      'Z_2' : tf.float32,
                                                      'M_2' : tf.float32,
                                                      'JDUTC_3' : tf.float32,
                                                      'X_3' : tf.float32,
                                                      'Y_3' : tf.float32,
                                                      'Z_3' : tf.float32,
                                                      'M_3' : tf.float32,
                                                      'JDUTC_4' : tf.float32,
                                                      'X_4' : tf.float32,
                                                      'Y_4' : tf.float32,
                                                      'Z_4' : tf.float32,
                                                      'M_4' : tf.float32,
                                                      'JDUTC_5' : tf.float32,
                                                      'X_5' : tf.float32,
                                                      'Y_5' : tf.float32,
                                                      'Z_5' : tf.float32,
                                                      'M_5' : tf.float32,
                                                      'JDUTC_6' : tf.float32,
                                                      'X_6' : tf.float32,
                                                      'Y_6' : tf.float32,
                                                      'Z_6' : tf.float32,
                                                      'M_6' : tf.float32,
                                                      'JDUTC_7' : tf.float32,
                                                      'X_7' : tf.float32,
                                                      'Y_7' : tf.float32,
                                                      'Z_7' : tf.float32,
                                                      'M_7' : tf.float32,
                                                      'JDUTC_8' : tf.float32,
                                                      'X_8' : tf.float32,
                                                      'Y_8' : tf.float32,
                                                      'Z_8' : tf.float32,
                                                      'M_8' : tf.float32,
                                                      'JDUTC_9' : tf.float32,
                                                      'X_9' : tf.float32,
                                                      'Y_9' : tf.float32,
                                                      'Z_9' : tf.float32,
                                                      'M_9' : tf.float32,
                                                      'mu_ra_0' : tf.float32,
                                                      'mu_dec_0' : tf.float32,
                                                      'mu_sq_0' : tf.float32,
                                                      'mu_ra_1' : tf.float32,
                                                      'mu_dec_1' : tf.float32,
                                                      'mu_sq_1' : tf.float32,
                                                      'mu_ra_2' : tf.float32,
                                                      'mu_dec_2' : tf.float32,
                                                      'mu_sq_2' : tf.float32,
                                                      'mu_ra_3' : tf.float32,
                                                      'mu_dec_3' : tf.float32,
                                                      'mu_sq_3' : tf.float32,
                                                      'mu_ra_4' : tf.float32,
                                                      'mu_dec_4' : tf.float32,
                                                      'mu_sq_4' : tf.float32,
                                                      'mu_ra_5' : tf.float32,
                                                      'mu_dec_5' : tf.float32,
                                                      'mu_sq_5' : tf.float32,
                                                      'mu_ra_6' : tf.float32,
                                                      'mu_dec_6' : tf.float32,
                                                      'mu_sq_6' : tf.float32,
                                                      'mu_ra_7' : tf.float32,
                                                      'mu_dec_7' : tf.float32,
                                                      'mu_sq_7' : tf.float32,
                                                      'mu_ra_8' : tf.float32,
                                                      'mu_dec_8' : tf.float32,
                                                      'mu_sq_8' : tf.float32})

header_features = tfds.features.FeaturesDict({'JDUTC_0' : tf.float32,
                                              'X_0' : tf.float32,
                                              'Y_0' : tf.float32,
                                              'Z_0' : tf.float32,
                                              'M_0' : tf.float32,
                                              'JDUTC_1' : tf.float32,
                                              'X_1' : tf.float32,
                                              'Y_1' : tf.float32,
                                              'Z_1' : tf.float32,
                                              'M_1' : tf.float32,
                                              'JDUTC_2' : tf.float32,
                                              'X_2' : tf.float32,
                                              'Y_2' : tf.float32,
                                              'Z_2' : tf.float32,
                                              'M_2' : tf.float32,
                                              'JDUTC_3' : tf.float32,
                                              'X_3' : tf.float32,
                                              'Y_3' : tf.float32,
                                              'Z_3' : tf.float32,
                                              'M_3' : tf.float32,
                                              'JDUTC_4' : tf.float32,
                                              'X_4' : tf.float32,
                                              'Y_4' : tf.float32,
                                              'Z_4' : tf.float32,
                                              'M_4' : tf.float32,
                                              'JDUTC_5' : tf.float32,
                                              'X_5' : tf.float32,
                                              'Y_5' : tf.float32,
                                              'Z_5' : tf.float32,
                                              'M_5' : tf.float32,
                                              'JDUTC_6' : tf.float32,
                                              'X_6' : tf.float32,
                                              'Y_6' : tf.float32,
                                              'Z_6' : tf.float32,
                                              'M_6' : tf.float32,
                                              'JDUTC_7' : tf.float32,
                                              'X_7' : tf.float32,
                                              'Y_7' : tf.float32,
                                              'Z_7' : tf.float32,
                                              'M_7' : tf.float32,
                                              'JDUTC_8' : tf.float32,
                                              'X_8' : tf.float32,
                                              'Y_8' : tf.float32,
                                              'Z_8' : tf.float32,
                                              'M_8' : tf.float32,
                                              'JDUTC_9' : tf.float32,
                                              'X_9' : tf.float32,
                                              'Y_9' : tf.float32,
                                              'Z_9' : tf.float32,
                                              'M_9' : tf.float32,
                                              'mu_ra_0' : tf.float32,
                                              'mu_dec_0' : tf.float32,
                                              'mu_sq_0' : tf.float32,
                                              'mu_ra_1' : tf.float32,
                                              'mu_dec_1' : tf.float32,
                                              'mu_sq_1' : tf.float32,
                                              'mu_ra_2' : tf.float32,
                                              'mu_dec_2' : tf.float32,
                                              'mu_sq_2' : tf.float32,
                                              'mu_ra_3' : tf.float32,
                                              'mu_dec_3' : tf.float32,
                                              'mu_sq_3' : tf.float32,
                                              'mu_ra_4' : tf.float32,
                                              'mu_dec_4' : tf.float32,
                                              'mu_sq_4' : tf.float32,
                                              'mu_ra_5' : tf.float32,
                                              'mu_dec_5' : tf.float32,
                                              'mu_sq_5' : tf.float32,
                                              'mu_ra_6' : tf.float32,
                                              'mu_dec_6' : tf.float32,
                                              'mu_sq_6' : tf.float32,
                                              'mu_ra_7' : tf.float32,
                                              'mu_dec_7' : tf.float32,
                                              'mu_sq_7' : tf.float32,
                                              'mu_ra_8' : tf.float32,
                                              'mu_dec_8' : tf.float32,
                                              'mu_sq_8' : tf.float32})

baseline_header = tfds.features.FeaturesDict({'JDUTC_0' : tf.float32,
                                              'X_0' : tf.float32,
                                              'Y_0' : tf.float32,
                                              'Z_0' : tf.float32,
                                              'M_0' : tf.float32,
                                              'JDUTC_1' : tf.float32,
                                              'X_1' : tf.float32,
                                              'Y_1' : tf.float32,
                                              'Z_1' : tf.float32,
                                              'M_1' : tf.float32,
                                              'mu_ra_0' : tf.float32,
                                              'mu_dec_0' : tf.float32,
                                              'mu_sq_0' : tf.float32})

baseline_header2 = ['NEO',
                    'X_0',
                    'Y_0',
                    'Z_0',
                    'M_0',
                    'X_1',
                    'Y_1',
                    'Z_1',
                    'M_1',
                    'X_2',
                    'Y_2',
                    'Z_2',
                    'M_2', 
                    'mu_ra_0',
                    'mu_dec_0',
                    'mu_sq_0',
                    'mu_ra_1',
                    'mu_dec_1',
                    'mu_sq_1']

header_shap = ['JDUTC_0',
'X_0',
'Y_0',
'Z_0',
'M_0',
'JDUTC_1',
'X_1',
'Y_1',
'Z_1',
'M_1',
'JDUTC_2',
'X_2',
'Y_2',
'Z_2',
'M_2',
'JDUTC_3',
'X_3',
'Y_3',
'Z_3',
'M_3',
'JDUTC_4',
'X_4',
'Y_4',
'Z_4',
'M_4',
'JDUTC_5',
'X_5',
'Y_5',
'Z_5',
'M_5',
'JDUTC_6',
'X_6',
'Y_6',
'Z_6',
'M_6',
'JDUTC_7',
'X_7',
'Y_7',
'Z_7',
'M_7',
'JDUTC_8',
'X_8',
'Y_8',
'Z_8',
'M_8',
'JDUTC_9',
'X_9',
'Y_9',
'Z_9',
'M_9',
'mu_ra_0',
'mu_dec_0',
'mu_sq_0',
'mu_ra_1',
'mu_dec_1',
'mu_sq_1',
'mu_ra_2',
'mu_dec_2',
'mu_sq_2',
'mu_ra_3',
'mu_dec_3',
'mu_sq_3',
'mu_ra_4',
'mu_dec_4',
'mu_sq_4',
'mu_ra_5',
'mu_dec_5',
'mu_sq_5',
'mu_ra_6',
'mu_dec_6',
'mu_sq_6',
'mu_ra_7',
'mu_dec_7',
'mu_sq_7',
'mu_ra_8',
'mu_dec_8',
'mu_sq_8']